### ISSUE TITLE
error with pm2 2.5.0

### ISSUE THREAD

**Issue by derEremit** [mattpker/pm2-slack#19]
`/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:130
    return typeof obj == 'object' && obj.width != undefined
                                        ^

TypeError: Cannot read property 'width' of null
    at get_width (/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:130:41)
    at /usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:125:68
    at Array.forEach (native)
    at extractColumnWidths (/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:124:9)
    at /usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:98:11
    at Array.forEach (native)
    at Table.toString (/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:95:16)
    at /usr/lib/node_modules/pm2/lib/API/CliUx.js:329:29
    at Array.forEach (native)
    at Object.UX.dispKeys (/usr/lib/node_modules/pm2/lib/API/CliUx.js:310:19)`

**Comment by mattpker** [comment]
That error looks like it's coming directly from PM2. Can you please give more details on how / when this error is occurring? I don't even see pm2-slack in the traceback, you sure this is a pm2-slack error? You may need to report it to the PM2 repo.

**Comment by mattpker** [comment]
Have not heard anything back, closing
